---
title: "Welcome to the Marine Biodiversity Observation Network!"
params:
  news_limit: 3
output:
  html_document:
    toc: false
---

```{r carousel, child="_carousel.Rmd"}
```

## Latest News

```{r news, child="_news.Rmd"}
```

## Sites

```{r map, echo=FALSE, message=FALSE}
library(readr)
library(dplyr)
library(leaflet)

# read sites, construct popup HTML
sites = read_csv('data/sites.csv') %>%
  mutate(
    popup_html = sprintf("<h2>%s</h2>\n <a href=%s>More</a>", site,  url))
label_directions = sprintf("'%s'", paste(sites$label_direction, collapse="','"))

# sites_nms = sites %>% filter(!site %in% c('Chukchi Sea','Santa Barbara Channel'))
# leaflet(data = sites_nms) %>%
leaflet(data = sites, height=300) %>%
  addProviderTiles('Stamen.TonerBackground') %>% # 'Esri.OceanBasemap'
  addMarkers(~lon, ~lat, popup = ~as.character(popup_html)) # %>%
  # addLabelOnlyMarkers(
  #   ~lon, ~lat, label=~as.character(site),
  #   labelOptions = labelOptions(
  #     #noHide = T, direction = 'auto', textsize = "20px"))
  #     noHide = T, direction = sites$label_direction, textsize = "20px")) # "direction":["right","left","right","left","right"]
      #noHide = T, direction = label_directions, textsize = "20px")) # ,"direction":"'right','left','right','left','right'",
      
```

